name: Publish Package

on:
    release:
        types: [published]

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1
            - uses: actions/setup-node@v4
              with:
                  registry-url: "https://registry.npmjs.org"
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Build
              run: bun install && bun run build
            - name: Publish to npm
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npm publish
